#asynqmon asynq延迟队列、定时队列的webui
asynqmon:
  image: hibiken/asynqmon:latest
  container_name: asynqmon
  ports:
    - 8086:8080
  command:
    - '--redis-addr=10.45.11.94:31599'
    - '--redis-password='
    - '--redis-db=2'
  restart: always
#    networks:
#      - looklook_net
#    depends_on:
#      - redis
